package domain;
// Generated May 20, 2018 11:40:06 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contract generated by hbm2java
 */
@Entity
@Table(name="Contract"
    ,catalog="dairy"
)
public class Contract  implements java.io.Serializable {


     private Integer contractId;
     private int supplierId;
     private String startDate;
     private String endDate;
     private float amountPerDay;
     private float unitCost;
     private String status;

    public Contract() {
    }

    public Contract(int supplierId, String startDate, String endDate, float amountPerDay, float unitCost, String status) {
       this.supplierId = supplierId;
       this.startDate = startDate;
       this.endDate = endDate;
       this.amountPerDay = amountPerDay;
       this.unitCost = unitCost;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="contractId", unique=true, nullable=false)
    public Integer getContractId() {
        return this.contractId;
    }
    
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    
    @Column(name="supplierId", nullable=false)
    public int getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(int supplierId) {
        this.supplierId = supplierId;
    }

    
    @Column(name="startDate", nullable=false, length=10)
    public String getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    
    @Column(name="endDate", nullable=false, length=10)
    public String getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="amountPerDay", nullable=false, precision=12, scale=0)
    public float getAmountPerDay() {
        return this.amountPerDay;
    }
    
    public void setAmountPerDay(float amountPerDay) {
        this.amountPerDay = amountPerDay;
    }

    
    @Column(name="unitCost", nullable=false, precision=12, scale=0)
    public float getUnitCost() {
        return this.unitCost;
    }
    
    public void setUnitCost(float unitCost) {
        this.unitCost = unitCost;
    }

    
    @Column(name="status", nullable=false, length=8)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


